int cols, rows;

FlowField f;
ArrayList<Particle> particles;

PImage background;

PVector[] flowField;
PVector mouse;
PVector center;
PVector newmouse;

DNA[] population = new DNA[100];

void setup()
{
  size(800, 600, P2D);
  f = new FlowField(15);

  background = loadImage("background.jpg");

  particles = new ArrayList<Particle>();

  for (int i = 0; i < 100; i++) {
    particles.add(new Particle(random(width), random(height)));
  }

  for (int i = 0; i < population.length; i++) {
    population[i] = new DNA();
  }
}

//adding a new ant every time mouse is pressed
void mouseClicked() {
  particles.add(new Particle(mouseX, mouseY));
}

void draw()
{
  background(210, 180, 140);
  background(background);


  for (Particle p : particles) {
    p.follow(f); // Apply the steering force to follow the flow field
    //p.seek();
    p.update(); // Update the velocity and location, based on the acceleration generated by the steering force
    p.show(); // display the vehicle
    p.getDNA();
  }
}
